services:
  - type: web
    name: localnest
    env: node
    plan: free

    buildCommand: npm install
    startCommand: npm start

    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000

      # Add these manually in Render Dashboard
      - key: ATLASDB_URL
        sync: false

      - key: ATLASDB_PASSWORD
        sync: false

      - key: SESSION_SECRET
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_KEY
        sync: false

      - key: CLOUDINARY_SECRET
        sync: false